apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: astro-app
  name: astro-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: astro-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: astro-app
    spec:
      containers:
        - env:
            - name: API_BASE_URL_INTERNAL
              value: http://api:8080
            - name: PUBLIC_API_BASE_URL
              value: https://api-overengineered.kishans.in
          image: ghcr.io/kishanhitk/overengineered-astro:latest
          name: astro-app
          ports:
            - containerPort: 4321
              protocol: TCP
      restartPolicy: Always

      imagePullSecrets:
        - name: github-registry
