apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: REDIS_URL
              value: dicedb:7379
          image: ghcr.io/kishanhitk/overengineered-api:latest
          name: api
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always

      imagePullSecrets:
        - name: github-registry
