name: Deploy Go API and Astro App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Test Go API
        run: |
          cd api
          go test -v ./...

      - name: Build Go API
        run: |
          cd api
          go build -v -o main .

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Astro dependencies
        run: |
          cd website
          bun install

      - name: Build Astro app
        run: |
          cd website
          echo "PUBLIC_API_BASE_URL=${{ secrets.PUBLIC_API_BASE_URL }}" > .env
          bun run build
        env:
          PUBLIC_API_BASE_URL: ${{ secrets.PUBLIC_API_BASE_URL }}

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "api/main,website/dist/**"
          target: "/var/www/overengineered/"
          strip_components: 1

      - name: Restart Services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            systemctl restart go-api
            systemctl restart astro-app
            systemctl restart nginx
            systemctl restart cloudflared
