name: Deploy Go API

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Test
        run: |
          cd api
          go test -v ./...

      - name: Debug SSH Key
        run: |
          echo "SSH key length: $(echo "${{ secrets.SSH_PRIVATE_KEY }}" | wc -l) lines"
          echo "SSH key start: $(echo "${{ secrets.SSH_PRIVATE_KEY }}" | head -n 1)"
          echo "SSH key end: $(echo "${{ secrets.SSH_PRIVATE_KEY }}" | tail -n 1)"
          echo "Key type: $(echo "${{ secrets.SSH_PRIVATE_KEY }}" | head -n 1 | cut -d ' ' -f 2)"

      - name: Build
        run: |
          cd api
          go build -v -o main .
      - name: Debug SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo "SSH connection successful"
            pwd
            whoami

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "api/main"
          target: "/var/www/overengineered/api/"
          strip_components: 1

      - name: Restart API
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            systemctl restart go-api
            systemctl restart cloudflared
